### PR TITLE
chore: Move modules for cross-org tests to this repository

### PR DESCRIPTION
**Pull request by jvfe**
Moves all modules and subworkflows used for testing in the old [test-subworkflow-remote](https://github.com/jvfe/test-subworkflow-remote/) repo to this repository, along with a schema file that should enable the [feature](https://github.com/nf-core/tools/pull/3083) being implemented.

### CODE REVIEW

**Review by muffato — COMMENTED** [review]
For the record, here is what we discussed earlier today:

- Briefly expand the README to explain the purpose of the repo.
- Only keep the files that are needed for the tests and to demonstrate the feature.

**Review by muffato — APPROVED** [review]

**Review by mirpedrol — APPROVED** [review]
You will have to add a `.nf-core.yml` file with the following information:
```
repository_type: modules
org_path: nf-core-test
```
Otherwise LGTM :)

**Review by mirpedrol — APPROVED** [review]
looks good, thanks!

**Comment by jvfe** [comment]
Thanks for the review, Júlia! I don't have write access to the repository though, so I can't merge this PR.

**Comment by mirpedrol** [comment]
Merged 😄 I also changed the permissions so you can merge in the future

**Pull request merged**
